# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink: pretty

# Setup
title: Swaptacular
tagline: 'The future of money'
description: >
  Free software which makes creation of digital currencies possible
  for everyone. No strings attached!
url: http://swaptacular.github.io

paginate: 10

excerpt_separator: '<!--more-->'

feed:
  excerpt_only: true
  posts_limit: 10

# Custom vars
version: 2.1.0

app_demo:
  debtors_webapp: https://demo.swaptacular.org/debtors-webapp
  creditors_webapp: https://demo.swaptacular.org/creditors-webapp

mailing_list:
  url: https://groups.io/g/swaptacular

github:
  repo: https://github.com/swaptacular
  utterances_repo_path: swaptacular/swaptacular.github.io
