# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: Swaptacular
tagline: 'The future of money'
description: >
  Free software for managing syndicated digital currencies
url: http://swaptacular.org

paginate: 2

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/epandurski/swaptacular
